[package]
publish = false
name = "zega-server"
version.workspace = true
edition.workspace = true

[dependencies]
axum = "0.7"
futures-util = { version = "0.3", default-features = false }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
subtle = "2.6"
reqwest = { version = "0.12", features = ["json", "gzip"] }
hmac = "0.12"
base64 = "0.22"
flate2 = "1"
tokio = { workspace = true, features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
zega = { workspace = true }

[dev-dependencies]
tempfile = "3"
