/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_zegawasm_free: (a: number, b: number) => void;
export const format: (a: number, b: number) => [number, number, number, number];
export const format_json: (a: number, b: number) => [number, number];
export const zegawasm_apply: (a: number, b: number, c: number) => [number, number, number, number];
export const zegawasm_apply_with_sources: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const zegawasm_check: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const zegawasm_connect: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const zegawasm_delete_node: (a: number, b: number) => [number, number];
export const zegawasm_delete_relationship: (a: number, b: number) => [number, number];
export const zegawasm_exportGraph: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const zegawasm_export_base64: (a: number) => [number, number, number, number];
export const zegawasm_graph: (a: number) => [number, number, number, number];
export const zegawasm_importGraph: (a: number, b: number, c: number) => [number, number, number, number];
export const zegawasm_import_base64: (a: number, b: number, c: number) => [number, number];
export const zegawasm_load_locations: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const zegawasm_new: () => [number, number, number];
export const zegawasm_nodes_expanded: (a: number) => [number, number, number];
export const zegawasm_preview_import: (a: number, b: number, c: number) => [number, number, number, number];
export const zegawasm_rows_examined: (a: number) => [number, number, number];
export const zegawasm_run: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const zegawasm_run_with_sources: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const zegawasm_schema: (a: number, b: number, c: number) => [number, number, number, number];
export const zegawasm_schema_diff: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const zegawasm_vector_view: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
